# High-level options
seed: 42                                  # Define the random seed for consistent results.
mlflow: false                             # Turn on/off mlflow for experiment tracking.
multi_gpu: true                           # If true, uses DataParallel to distribute computation to multiple GPUs

# Define model and data options
model_mode: resnet50                      # If there are multiple models, define which one to use. Three Options: resnet50, resnet18, contrastive_encoder
unlabelled_data: True                     # If True, training loader can use all unlabelled data in addition to labelled ones
                                          # Else, it will only use labelled training data
# Data and results paths
paths:                                    #
    data: ./data/                         # Where the data is stored.
    results: ./results/                   # Where the results such as trained model, and plots will be saved.
